# Generated by Django 2.2.16 on 2022-05-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mx_multilingual_discovery', '0003_auto_20220502_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilingualdiscovery',
            name='course_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multilingual_course', to='course_metadata.CourseRun', verbose_name='Course Title'),
        ),
        migrations.AlterField(
            model_name='multilingualdiscovery',
            name='program_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multilingual_program', to='course_metadata.Program', verbose_name='Program Title'),
        ),
    ]
