# Generated by Django 2.2.16 on 2022-06-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mx_multilingual_discovery', '0007_auto_20220531_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilingualdiscovery',
            name='course_title',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multilingual_course', to='course_metadata.CourseRun'),
        ),
    ]
