# Generated by Django 2.2.16 on 2022-06-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mx_multilingual_discovery', '0008_auto_20220601_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilingualdiscovery',
            name='course_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multilingual_course', to='course_metadata.CourseRun', verbose_name='Course Title'),
        ),
    ]
