# Generated by Django 2.2.16 on 2022-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0257_auto_20220722_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogram',
            name='program_language',
            field=models.CharField(db_index=True, help_text='The Language of this Program.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_language',
            field=models.CharField(db_index=True, help_text='The Language of this Program.', max_length=255, null=True),
        ),
    ]
